FROM	nginx:latest
RUN	mkdir -p /webconfig/
COPY	deployment/composeexample.conf /webconfig/
COPY	deployment/uwsgi_params /webconfig/
RUN	rm /etc/nginx/conf.d/default.conf \
		&& ln -s /webconfig/composeexample.conf /etc/nginx/conf.d/default.conf 
